### PR TITLE
Update to v123.1

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@muelli hello, hope you don't mind me making a comment here. I tried to contact you via email, but it kept saying "Undelivered" for some reason.

Anyway, does it bother you if I can maintain the flatpak as well? Since I've been the one submitting most of the MRs, I'd like the MRs to be pushed as soon as submitted so the updates get published as soon as possible.

**Comment by muelli** [comment]
no, not at all. You're doing good work. Thanks! I have not the power to edit the list of people with power to push to this repository, though. Let's ask @barthalion to add you.
I'd appreciate if you continue doing MRs to let the bot build the flatpak before pushing to master. Thanks.

reg. the email address, what address have you tried? Maybe I do indeed have a problem with my setup.

**Comment by TheEvilSkeleton** [comment]
> reg. the email address, what address have you tried? Maybe I do indeed have a problem with my setup.

I've tried tobiasmue@gnome.org since it was the one in the metadata file.

> I'd appreciate if you continue doing MRs to let the bot build the flatpak before pushing to master. Thanks.

Will do.

**Comment by barthalion** [comment]
@TheEvilSkeleton You should receive an invitation soonish.

**Pull request merged**
