### PR TITLE
Add SDL2 with libdecor for Wayland support

### PR DESCRIPTION
**Pull request by orowith2os**
See https://github.com/flathub/com.github.Anuken.Mindustry/issues/59

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Any reason why this is a draft?

**Comment by orowith2os** [comment]
Needed some upstream work iirc, and didn't work

**Comment by orowith2os** [comment]
Also, 23.08 has libdecor and SDL2 already

**Comment by TheEvilSkeleton** [comment]
So it's safe to close this MR right?

**Pull request closed without merging**
