### PR TITLE
Add automatic dependency updater

### PR DESCRIPTION
**Pull request by TobTobXX**
How do I test GHA cron jobs?

(I'm bad with GHA.)

### CODE REVIEW

**Comment by TobTobXX** [comment]
:facepalm:

**Comment by TobTobXX** [comment]
bot, stop

**Comment by TobTobXX** [comment]
bot, help

**Comment by TobTobXX** [comment]
bot, ur stupid

**Comment by TobTobXX** [comment]
see, toldya

**Comment by TobTobXX** [comment]
Imma close this or I'll flood the flathub build server...

**Comment by TheEvilSkeleton** [comment]
> How do I test GHA cron jobs?
> 
> (I'm bad with GHA.)

Sadly, we can't.

**Comment by TobTobXX** [comment]
I got it to work, but it has to be on the default branch. :roll_eyes:

**Comment by TheEvilSkeleton** [comment]
Is there a reason why this was closed?

**Comment by TobTobXX** [comment]
Yeah, I don't wanna test the GHA on a PR where the flathubbot will always try to build it again.

**Pull request closed without merging**
