### PR TITLE
Add flatpak-external-data-checker support

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
The title says all. [I added Mindustry in release-monitoring.org](https://release-monitoring.org/project/147357/), so we should be getting the latest releases automatically once merged.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
So changing the manifest to:

```diff
-        url: https://github.com/Anuken/Mindustry/releases/download/v123.1/Mindustry.jar
-        sha256: 7b176abc92495884408c8c021ec65216326070354c1bece88245431ef77a9b2c
+        url: https://github.com/Anuken/Mindustry/releases/download/v123.1/Mindustry.jar
+        sha256: 7b176abc92495884408c8c021ec65216326070354c1bece88245431ef77a9b2d
```

(Changed sha256 to make it broken)

Results:
```bash
$ flatpak run org.flathub.flatpak-external-data-checker com.github.Anuken.Mindustry.yml
BROKEN: Mindustry.jar
 Has a new version:
  URL:     https://github.com/Anuken/Mindustry/releases/download/v123.1/Mindustry.jar
  SHA256:  7b176abc92495884408c8c021ec65216326070354c1bece88245431ef77a9b2c
  Size:    72019955
  Version: None
```
It seems to be working.

**Comment by TheEvilSkeleton** [comment]
Changing the manifest to:

```diff
-        url: https://github.com/Anuken/Mindustry/releases/download/v123.1/Mindustry.jar
-        sha256: 7b176abc92495884408c8c021ec65216326070354c1bece88245431ef77a9b2c
+        url: https://github.com/Anuken/Mindustry/releases/download/v123/Mindustry.jar
+        sha256: 632b31c61ea95c1a8f43139ef7d982db076c49c52313e9e18378a76250055412
```
(Downgrading the binary)

Results:
```bash
$ flatpak run org.flathub.flatpak-external-data-checker com.github.Anuken.Mindustry.yml
$
```
It means it does not automatically check the latest version.

**Comment by gasinvein** [comment]
The flatpak build of flatpak-external-data-checker wasn't updated for some time. It doesn't support anitya type checker data and just ignores it, only checking if the specified url matches checksum.

**Comment by TheEvilSkeleton** [comment]
Thank you. I just ran it and it seems to be working.

**Comment by muelli** [comment]
woahr. Excellent! Thank you so much! <3

**Pull request merged**
